// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptPsw(arg1, arg2) {
  return window['go']['main']['App']['DecryptPsw'](arg1, arg2);
}

export function GenerateSafePassword(arg1) {
  return window['go']['main']['App']['GenerateSafePassword'](arg1);
}

export function GetPasswordForUser(arg1) {
  return window['go']['main']['App']['GetPasswordForUser'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Register(arg1, arg2) {
  return window['go']['main']['App']['Register'](arg1, arg2);
}

export function SaveCredentials(arg1, arg2) {
  return window['go']['main']['App']['SaveCredentials'](arg1, arg2);
}
