// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateSafePassword(arg1:number):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function Login(arg1:string,arg2:string):Promise<string>;

export function Register(arg1:string,arg2:string):Promise<string>;
