// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mongodb} from '../models';

export function DecryptPsw(arg1:string,arg2:string):Promise<string>;

export function GenerateSafePassword(arg1:number):Promise<string>;

export function GetPasswordForUser(arg1:string):Promise<Array<mongodb.Credentials>>;

export function Greet(arg1:string):Promise<string>;

export function Login(arg1:string,arg2:string):Promise<string>;

export function Register(arg1:string,arg2:string):Promise<string>;

export function SaveCredentials(arg1:mongodb.User,arg2:mongodb.Credentials):Promise<string>;
